export const SEARCH_FOCUS = 'search/search_focus'
export const SEARCH_BLUR = 'search/search_blur'
export const CHANGE_LIST = 'search/change_list'
export const SEARCH_HOT_LIST = 'search/search_hot_out'
export const CHANGE_PAGE = 'search/change_page'